### ISSUE TITLE
Too slow even with provisioned provisioned concurrency

### ISSUE THREAD

**Issue by hopewise** [rails-lambda/lamby#159]
Hello

I have added 4 provisioned concurrencies, with 650MB, but even so, I notice its too slow to start, is there any recommendations? Is there anyone used with Rails app in a good performance ?

**Comment by metaskills** [comment]
Have you read this guide? https://lamby.custominktech.com/docs/cold-starts?

At a minimal, your Rails Lambda should be at 1792 which is 1vCPU. I'd be curious to hear why you need provisioned concurrency too. Lots of details please.

**Comment by metaskills** [comment]
FYI, I just transferred the docs site to lamby.cloud. So that link above might have been broken for a few hours. Should be working now with redirects.

**Comment by hopewise** [comment]
Thanks @metaskills , that was useful to point out, I have set memory to 1792, much faster, but still can be faster if I use the right web server, currently, I am using Puma as the web server, built for parallelism, but it will not useful to use in AWS Lambda. 

Do you recommend any fast web server other than Puma? Any suggestions to make the Rails app bootstrapping faster would be appreciated.

**Comment by hopewise** [comment]
Thanks for explaining, as I have already deployed my Rails app to an EC2 cluster, I was relying on a web server, I just forgot that I will not needed it on Lambda as being a Rack application.

**Comment by metaskills** [comment]
Cool, let me know what you find out with the cold starts and how your workloads might differ from the assessment in the guides. We can always amend them with other's knowledge and use cases.
