### ISSUE TITLE
The "existing" link on the Quickstart page does not link to instructions on working with an existing Rails app

### ISSUE THREAD

**Issue by randall-coding** [rails-lambda/lamby#175]
![Screenshot from 2024-03-05 13-40-58](https://github.com/rails-lambda/lamby/assets/39175191/0eb590f4-4459-45db-9c4e-02db5657aa23)

Clicking "existing" takes us to the "How Lamby Works" section which on my reading of it didn't provide a clear path to get started on adding lamby to an existing project.  

I would have expected a guide like this one https://blog.devops.dev/how-to-setup-ruby-on-rails-with-aws-lambda-using-the-lamby-gem-serverless-application-8a7fc024ae15 which goes step by step showing what to do.  Just thought I'd point that out and suggest you could make a similar guide for an existing Rails app.

**Comment by jeremiahlukus** [comment]
Its kind of a lot of code to put in a blog. 

here is a repo i made the first commit its rails create the second is adding a full  lamby example 


https://github.com/jeremiahlukus/rails-serverless/commit/45613aadcf123eb04b129519cb11d0d56bd1c127
