### ISSUE TITLE
Execution failed due to configuration error: Malformed Lambda proxy response

### ISSUE THREAD

**Issue by Ragnarow** [rails-lambda/lamby#78]
After upgrading Lamby I have the following error in API Gateway:

```Execution failed due to configuration error: Malformed Lambda proxy response```

This is because the output for the Lamby lambda function contains a key 'cookies' that is not supposed to be there according to the [AWS doc](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html), format must be:

```json
{
    "isBase64Encoded": true|false,
    "statusCode": httpStatusCode,
    "headers": { "headerName": "headerValue", ... },
    "multiValueHeaders": { "headerName": ["headerValue", "headerValue2", ...], ... },
    "body": "..."
}
```

This is most likely due to this commit: https://github.com/customink/lamby/commit/5fdb0c4bedc57356dea242a4486a1e121a38628f

My output before the upgrade:

```
{
	"statusCode": 200,
	"headers": {
		"X-Frame-Options": "SAMEORIGIN",
		"X-XSS-Protection": "1; mode=block",
		"X-Content-Type-Options": "nosniff",
		"X-Download-Options": "noopen",
		"X-Permitted-Cross-Domain-Policies": "none",
		"Referrer-Policy": "strict-origin-when-cross-origin",
		"Content-Type": "text/html; charset=utf-8",
		"Set-Cookie": "...",
		"ETag": "...",
		"Cache-Control": "max-age=0, private, must-revalidate",
		"X-Request-Id": "...",
		"X-Runtime": "0.003934"
	},
	"body": "<!DOCTYPE html>..."
}
```

And after the upgrade:
```
{
	"statusCode": 200,
	"headers": {
		"X-Frame-Options": "SAMEORIGIN",
		"X-XSS-Protection": "1; mode=block",
		"X-Content-Type-Options": "nosniff",
		"X-Download-Options": "noopen",
		"X-Permitted-Cross-Domain-Policies": "none",
		"Referrer-Policy": "strict-origin-when-cross-origin",
		"Content-Type": "text/html; charset=utf-8",
		"ETag": "...",
		"Cache-Control": "max-age=0, private, must-revalidate",
		"X-Request-Id": "...",
		"X-Runtime": "0.003851"
	},
	"body": "<!DOCTYPE html>...",
	"cookies": [
		"_interslice_session...",
		"_interslice_session=..."
	]
}
```

**Comment by metaskills** [comment]
Sorry for the slow reply. Which version of API Gateway are you using and if HTTP API what payload version? I am guessing REST API given the doc link. 

We have not seen this yet because likely our REST APIs are not doing any set cookies.... yet. Do you have any ideas on what to change in https://github.com/customink/lamby/commit/5fdb0c4bedc57356dea242a4486a1e121a38628f to fix this?

**Comment by metaskills** [comment]
cc @avinash-vllbh

**Comment by metaskills** [comment]
Closing because so far I have not been able to reproduce this error locally. Please add comments and re-open as needed.

**Comment by jeremiahlukus** [comment]
I’ll make a patch either tonight or tomorrow, and write a test so it won’t get added again. 


When I patch can you test in your app to make sure it’s fixed?

**Comment by cpcwood** [comment]
@jeremiahlukus yes, I can test the patch once added 👍🏻

**Comment by jeremiahlukus** [comment]
Ok can you pull from my fork. 

https://github.com/jeremiahlukus/lamby


Seems like i added that to the rack_response on the last release. Im not sure why it didnt break for me and the other person that tested it.

**Comment by cpcwood** [comment]
@jeremiahlukus I've pulled from your fork with `gem 'lamby', :git => 'https://github.com/jeremiahlukus/lamby.git'` and can confirm this is now working. Thank you!

I wonder if you are using a different type of lambda integration/api gateway (I've not looked into the options), if you are interested my project uses the following terraform code to proxy to the lambda:

```tf
# proxy requests to the api gateway root - e.g. /
resource "aws_api_gateway_method" "lambda_proxy_root" {
  rest_api_id   = aws_api_gateway_rest_api.lambda_proxy.id
  resource_id   = aws_api_gateway_rest_api.lambda_proxy.root_resource_id
  http_method   = "ANY"
  authorization = "NONE"
}

resource "aws_api_gateway_integration" "lambda_proxy_root" {
  rest_api_id = aws_api_gateway_rest_api.lambda_proxy.id
  resource_id = aws_api_gateway_method.lambda_proxy_root.resource_id
  http_method = aws_api_gateway_method.lambda_proxy_root.http_method

  integration_http_method = "POST"
  type                    = "AWS_PROXY"
  uri                     = aws_lambda_function.lambda.invoke_arn
}
```

**Comment by jeremiahlukus** [comment]
Sweet, I’ll send the PR today, and try to get it released in the next day or so . Thank you for testing.

**Comment by jeremiahlukus** [comment]
@cpcwood  its merged and released now
